## Исследование биоинформатических данных

### Данные генной экспрессии больних.

In [2]:
%pylab inline
import pandas as pd

Populating the interactive namespace from numpy and matplotlib

In [3]:
gene_expr_transposed = pd.read_csv('CLCE/CLCE_filtered_75.expr.csv', sep='\t')
gene_expr_transposed.head()

,UNIT_ID,UnitName,EntrezID,GeneSymbol,GSM886835,GSM886836,GSM886837,GSM886838,GSM886839,GSM886840,...,GSM887742,GSM887743,GSM887744,GSM887745,GSM887746,GSM887747,GSM887748,GSM887749,GSM887750,GSM887751
0,10094,210565_at,2642,GCGR,16.7570,16.9059,17.7288,15.5074,17.4813,21.3226,...,15.4918,12.8077,19.2298,21.2812,16.3212,15.8719,15.3871,17.7318,15.8485,18.1507
1,10303,210782_x_at,2902,GRIN1,39.9733,36.8459,37.5814,31.3759,24.9784,33.7708,...,26.8515,42.2028,28.2526,51.2598,28.0117,26.1901,20.5035,34.5061,28.9217,33.3171
2,10320,210799_at,3351,HTR1B,17.0582,17.5766,18.0595,19.1959,14.9803,16.1253,...,14.8634,17.8169,22.7556,21.1638,19.1880,17.2848,18.8022,19.2399,15.6619,23.0964
3,10447,210939_s_at,2911,GRM1,16.6820,15.0696,14.3185,16.3369,16.8618,15.5227,...,13.4785,17.2449,13.9253,16.5428,15.3139,12.4469,12.8386,18.9590,18.1510,21.5692
4,10464,210956_at,5540,PPYR1,17.0133,21.6207,20.7412,19.6524,20.4569,23.6259,...,20.4548,16.7650,19.4700,26.3223,19.6747,21.6940,14.1549,30.3307,18.2650,24.5604

In [5]:
gene_expr = gene_expr_transposed.transpose()
gene_expr.head()

,0,1,2,3,4,5,6,7,8,9,...,189,190,191,192,193,194,195,196,197,198
UNIT_ID,10094,10303,10320,10447,10464,10469,10551,10676,10717,10726,...,9586,9623,9668,9724,9730,9776,9942,9951,9971,9993
UnitName,210565_at,210782_x_at,210799_at,210939_s_at,210956_at,210961_s_at,211046_at,211173_at,211217_s_at,211226_at,...,210040_at,210078_s_at,210123_s_at,210179_at,210185_at,210234_at,210403_s_at,210412_at,210432_s_at,210454_s_at
EntrezID,2642,2902,3351,2911,5540,146,81033,886,3784,8811,...,57468,7881,1139,3769,782,2914,3758,2904,6328,3763
GeneSymbol,GCGR,GRIN1,HTR1B,GRM1,PPYR1,ADRA1D,KCNH6,CCKAR,KCNQ1,GALR2,...,SLC12A5,KCNAB1,CHRFAM7A,KCNJ13,CACNB1,GRM4,KCNJ1,GRIN2B,SCN3A,KCNJ6
GSM886835,16.757,39.9733,17.0582,16.682,17.0133,12.9442,19.7561,38.4805,45.8128,10.3816,...,16.018,22.6837,25.4747,12.9362,51.6119,21.0572,17.0367,21.0679,221.06,17.7502

In [6]:
gene_expr.columns = gene_expr.iloc[2]
gene_expr.drop(['UNIT_ID', 'UnitName', 'EntrezID', 'GeneSymbol'], axis=0, inplace=True)
gene_expr.head()

EntrezID,2642,2902,3351,2911,5540,146,81033,886,3784,8811,...,57468,7881,1139,3769,782,2914,3758,2904,6328,3763
GSM886835,16.757,39.9733,17.0582,16.682,17.0133,12.9442,19.7561,38.4805,45.8128,10.3816,...,16.018,22.6837,25.4747,12.9362,51.6119,21.0572,17.0367,21.0679,221.06,17.7502
GSM886836,16.9059,36.8459,17.5766,15.0696,21.6207,14.7328,19.9867,47.4208,47.3419,11.489,...,13.3076,33.1699,33.8101,12.2244,34.389,16.3105,12.8219,22.3526,10.3724,14.7599
GSM886837,17.7288,37.5814,18.0595,14.3185,20.7412,10.5136,33.0547,47.2341,41.4062,12.7074,...,14.3692,35.4226,22.7934,14.248,24.7173,15.9595,14.8595,18.6059,11.303,16.4502
GSM886838,15.5074,31.3759,19.1959,16.3369,19.6524,9.96036,20.5418,45.0763,54.138,11.3183,...,13.5791,24.2979,33.519,11.0078,21.1186,15.6265,14.9448,18.1387,9.91897,15.4157
GSM886839,17.4813,24.9784,14.9803,16.8618,20.4569,11.5444,21.9831,39.8305,45.9178,12.2775,...,16.735,35.0732,24.64,12.2853,32.4037,20.2636,18.3912,18.2372,11.9405,14.4225

In [7]:
sample_info = pd.read_csv('CLCE/CLCE_Samples_Sort_Descr.csv', sep=',')
sample_info.set_index(sample_info['Sample'], inplace=True)
sample_info.head()

              Sample                   Organ       Type               Subtype
Sample
GSM887751  GSM887751                  breast  carcinoma     ductal_carcinomas
GSM887750  GSM887750                  breast  carcinoma      ductal_carcinoma
GSM887749  GSM887749                  breast  carcinoma                   NaN
GSM887748  GSM887748  central_nervous_system     glioma  astrocytoma_Grade_IV
GSM887747  GSM887747  central_nervous_system     glioma  astrocytoma_Grade_IV

In [8]:
target = sample_info[['Organ']]
target.head()

                            Organ
Sample
GSM887751                  breast
GSM887750                  breast
GSM887749                  breast
GSM887748  central_nervous_system
GSM887747  central_nervous_system